### ISSUE TITLE
Java Naming convertion for methods

### ISSUE THREAD

**Issue by khda91** [tanya00pm/Homework-1_task-2#1]
https://github.com/tanya00pm/Homework-1_task-2/blob/a1289bede5dc6978420cdc7978651ae100844cd8/BinarySearchApplication.java#L32
https://github.com/tanya00pm/Homework-1_task-2/blob/a1289bede5dc6978420cdc7978651ae100844cd8/BinarySearch.java#L11
https://github.com/tanya00pm/Homework-1_task-2/blob/a1289bede5dc6978420cdc7978651ae100844cd8/BinarySearch.java#L16

Обратите пожалуйста внимание на правила именования методов в Java.
https://drive.google.com/file/d/1psN0db7O4GT95OxudCCx1pV9igtq2ofY/view?usp=sharing

**Comment by tanya00pm** [comment]
Поправлено

**Comment by khda91** [comment]
closed
